<a href="https://colab.research.google.com/github/anuvrat-umich/siads_milestone1/blob/anuvrat/input_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exploring inputs

#### Importing libraries

In [5]:
### Defining libraries
import pandas as pd

#### Importing datasets to be used

In [6]:
input_path="..\input"

In [7]:
#Census income levels
#Income in the Past 12 Months (in 2022 Inflation-Adjusted Dollars) : ACSST5Y2022.S1901
df_income_1902=pd.read_csv(input_path+"\ACSST5Y2022-S1901-Data.csv")
df_income_1902.head(5)

FileNotFoundError: [Errno 2] No such file or directory: '..\\input\\ACSST5Y2022-S1901-Data.csv'

In [ ]:
#Health Outcomes
df_health_outcomes=pd.read_csv(input_path+"\PLACES__Local_Data_for_Better_Health__ZCTA_Data_2023_release_20240127.csv")
df_health_outcomes.head(5)

C:\Users\Anuvrat\AppData\Local\Temp\ipykernel_23304\3245527026.py:2: DtypeWarning: Columns (8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_health_outcomes=pd.read_csv("..\input\PLACES__Local_Data_for_Better_Health__ZCTA_Data_2023_release_20240127.csv")

,Year,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Data_Value_Footnote_Symbol,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
0,2021,1001,BRFSS,Prevention,Current lack of health insurance among adults ...,%,Crude prevalence,4.1,NaN,NaN,3.4,5.0,16769,POINT (-72.62581515 42.06255509),1001,PREVENT,ACCESS2,CrdPrv,Health Insurance
1,2021,1001,BRFSS,Health Outcomes,Arthritis among adults aged >=18 years,%,Crude prevalence,33.7,NaN,NaN,30.1,37.4,16769,POINT (-72.62581515 42.06255509),1001,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis
2,2021,1001,BRFSS,Health Risk Behaviors,Binge drinking among adults aged >=18 years,%,Crude prevalence,15.6,NaN,NaN,13.2,18.2,16769,POINT (-72.62581515 42.06255509),1001,RISKBEH,BINGE,CrdPrv,Binge Drinking
3,2021,1001,BRFSS,Health Outcomes,High blood pressure among adults aged >=18 years,%,Crude prevalence,33.8,NaN,NaN,30.2,37.4,16769,POINT (-72.62581515 42.06255509),1001,HLTHOUT,BPHIGH,CrdPrv,High Blood Pressure
4,2021,1001,BRFSS,Prevention,Taking medicine for high blood pressure contro...,%,Crude prevalence,78.9,NaN,NaN,75.7,81.8,16769,POINT (-72.62581515 42.06255509),1001,PREVENT,BPMED,CrdPrv,Taking BP Medication

In [ ]:
#Social Determinants of Health
df_sdoh=pd.read_csv(input_path+"\SDOH_Measures_for_ZCTA__ACS_2017-2021_20240121.csv")
df_sdoh.head(5)

,Year,LocationName,DataSource,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,MOE,TotalPopulation,LocationID,CategoryID,MeasureID,DataValueTypeID,Short_Question_Text,Geolocation
0,2017-2021,93420,5-year ACS,SDOH,Crowding among housing units,%,Percentage,2.3,1.2,31864,93420,SDOH,CROWD,Percent,Crowding,POINT (-120.476757 35.1760107)
1,2017-2021,6120,5-year ACS,SDOH,No broadband internet subscription among house...,%,Percentage,29.3,7.1,13399,6120,SDOH,BROAD,Percent,No broadband,POINT (-72.6648369 41.787198)
2,2017-2021,1810,5-year ACS,SDOH,Housing cost burden among households,%,Percentage,15.8,2.3,35600,1810,SDOH,HCOST,Percent,Housing cost burden,POINT (-71.1617514 42.6480437)
3,2017-2021,4259,5-year ACS,SDOH,Housing cost burden among households,%,Percentage,28.6,15.2,3279,4259,SDOH,HCOST,Percent,Housing cost burden,POINT (-70.0147235 44.2335047)
4,2017-2021,1128,5-year ACS,SDOH,Persons of racial or ethnic minority status,%,Percentage,34.8,10.2,3232,1128,SDOH,REMNRTY,Percent,Racial or ethnic minority status,POINT (-72.4891351 42.0922958)

In [ ]:
#Policital affiliation by state    ### You will need to install openpyxl for read_excel to work
df_state_politics=pd.read_excel(input_path+"\States Political Affiliations Jan-2024.xlsx", sheet_name="Data")
df_state_politics.head(5)

,STATE(TERRITORY),Abbreviation,Political Affiliation (2008-2020 presidential elections)
0,California,CA,Deep Blue
1,Colorado,CO,Deep Blue
2,Connecticut,CT,Deep Blue
3,Delaware,DE,Deep Blue
4,District of Columbia,DC,Deep Blue

In [ ]:
#Public health spending by state
df_state_public_spend=pd.read_csv(input_path+"\Per person state public health funding.csv", skiprows=6, dtype={'Fips': 'string'})
df_state_public_spend.head(5)

  Fips Location  TimeFrame Data Type      Data  MOE
0   01  Alabama       2017   Dollars  56.43214  NaN
1   01  Alabama       2018   Dollars  57.23000  NaN
2   01  Alabama       2019   Dollars  54.25000  NaN
3   01  Alabama       2020   Dollars  46.81000  NaN
4   01  Alabama       2021   Dollars  52.35000  NaN

In [ ]:
#American Community Survey : ACSDP5Y2020.DP05
df_acs=pd.read_csv(input_path+"\ACSDP5Y2020.DP05-Data.csv", skiprows=1)
df_acs.head(5)

C:\Users\Anuvrat\AppData\Local\Temp\ipykernel_23304\4140081384.py:2: DtypeWarning: Columns (3,5,7,11,17,19,21,23,25,31,39,43,49,51,53,55,59,61,63,67,127,141,143,153) have mixed types. Specify dtype option on import or set low_memory=False.
  df_acs=pd.read_csv("..\input\ACSDP5Y2020.DP05-Data.csv", skiprows=1)

,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),Margin of Error!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females),...,"Percent Margin of Error!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races",Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent Margin of Error!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent Margin of Error!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male","Percent!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female","Percent Margin of Error!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female",Unnamed: 358
0,8600000US00601,ZCTA5 00601,16773,259,8318,173,8455,199,98.4,3.1,...,0.3,(X),(X),13421,(X),48.1,0.7,51.9,0.7,NaN
1,8600000US00602,ZCTA5 00602,37083,149,18149,70,18934,112,95.9,0.6,...,0.4,(X),(X),30430,(X),48.7,0.2,51.3,0.2,NaN
2,8600000US00603,ZCTA5 00603,45652,784,22182,435,23470,446,94.5,1.7,...,0.2,(X),(X),36770,(X),48.0,0.5,52.0,0.5,NaN
3,8600000US00606,ZCTA5 00606,6231,337,3075,226,3156,180,97.4,7.2,...,0.8,(X),(X),5007,(X),49.7,2.1,50.3,2.1,NaN
4,8600000US00610,ZCTA5 00610,26502,137,12784,63,13718,77,93.2,0.2,...,0.5,(X),(X),21725,(X),47.6,0.2,52.4,0.2,NaN

#### Keeping only selected fields and renaming them

In [ ]:
df_income_1902